### ISSUE TITLE
FilmLight technical note : Standard Colour Spaces

### ISSUE THREAD

**Issue by remia** [colour-science/awesome-colour#2]
Hi,

I don't know if this can be added, because it may disappear at any time I guess, but this document is a very good intro I think : https://www.filmlight.ltd.uk/pdf/whitepapers/FL-TL-TN-0417-StdColourSpaces.pdf

**Comment by thomasmansencal** [comment]
Hi Remi,

Absolutely! Feel free to open a PR, the paper is on the Internet Wayback Machine already and I have a copy :)

**Comment by remia** [comment]
I's done ;)
